#!/usr/bin/env bash
#
# Generate protobuf gRPC bindings.

set -euxo pipefail

proto_src=api/proto
proto_dst=pkg/goph
docs_dst=docs/api

protoc \
    --proto_path=${proto_src} \
    --go_out=${proto_dst} \
    --go_opt=paths=source_relative \
    --go-grpc_out=${proto_dst} \
    --go-grpc_opt=paths=source_relative \
    --doc_out=${docs_dst} \
    --doc_opt=html,index.html \
    ${proto_src}/*.proto
